import { Person } from '../types/types'

export const vehicle = ['111', '143']

export const infrastructure = [
  'FV-DB',
  'FV-NE',
  'ZLB',
  'SZB',
  'Steilstreckenbetrieb',
  'PZB',
  'LZB',
  'LZB CE',
  'GNT',
  'FFB',
  'ETCS Stufe 1',
  'ETCS Stufe 2',
  'ETCS Stufe 3',
  'ZBS',
  'H/V',
  'Hl',
  'Ks',
  'Sv',
  'Sk',
  // 'GNT',
]

export const languages = [
  'Deutsch',
  'Englisch',
  'Französisch',
  'Spanisch',
  'Italienisch',
  'Niederländisch',
  'Portugiesisch',
  'Russisch',
  'Chinesisch',
  'Japanisch',
  'Koreanisch',
  'Arabisch',
  'Türkisch',
  'Hindi',
  'Bengalisch',
  'Punjabi',
  'Urdu',
  'Vietnamesisch',
  'Persisch',
  'Thai',
  'Griechisch',
  'Schwedisch',
  'Norwegisch',
  'Dänisch',
  'Finnisch',
  'Ungarisch',
  'Tschechisch',
  'Slowakisch',
  'Polnisch',
  'Rumänisch',
  'Bulgarisch',
  'Serbisch',
  'Kroatisch',
  'Slowenisch',
  'Litauisch',
  'Lettisch',
  'Estnisch',
  'Maltesisch',
  'Isländisch',
  'Irisch',
  'Walisisch',
  'Schottisch-Gälisch',
  'Hebräisch',
  'Jiddisch',
  'Afrikaans',
  'Swahili',
  'Zulu',
  'Xhosa',
  'Igbo',
  'Yoruba',
  'Hausa',
  'Amharisch',
  'Somali',
  'Madagassisch',
]

export const fakeData: Person[] = [
  {
    id: 1,
    fuehrerschein: {
      fuehrerscheinNummer: '0',
      status: 'gültig',
    },
    inhaber: {
      name: 'Mustermann',
      vorname: 'Max',
      geburtstag: new Date('1990-01-01'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 0,
      status: 'gültig',
      unbefristet: false,
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Straßenverkehrsamt Musterstadt',
      strasseUndNummer: 'Hauptstraße 1',
      plz: 12345,
      ort: 'Musterstadt',
      telefon: '01234-56789',
      fax: '01234-56789',
      email: 'info@strassenverkehrsamt-musterstadt.de',
    },
    bilder: {
      lichtBild: '',
      unterschrift: '',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma GmbH',
      strasseUndNummer: 'Industriestraße 10',
      plz: 54321,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '09876-54321',
      fax: '01234-56789',
      email: 'info@musterfirma.de',
      unternehmensKategorie: 'Dienstleistungen',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: true,
      A1: false,
      A2: false,
      A3: false,
      A4: false,
      A5: false,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: '',
    },
    zusaetzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschraenkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    aenderung: {
      datum: new Date('2023-06-01'),
      aenderungFeld3Klasse: 'Neue Klasse hinzugefügt: C',
      aenderungFeld4Angaben: 'Wohnort geändert',
      aenderungFeld5Sprachen: 'Spanisch hinzugefügt',
      aenderungFeld6Einschraenkung: 'Sehhilfe erforderlich',
      aenderungFeld7Fahrzeug: 'Neuer Fahrzeugtyp: LKW',
      aenderungFeld8Infrastruktur: 'Neuer Infrastrukturort hinzugefügt: Berlin',
      sontiges: 'Weitere Änderungen nicht relevant.',
    },
    aussetzung: {
      von: new Date('2023-07-01'),
      bis: new Date('2023-12-31'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: false,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: false,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: false,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: false,
      sontiges: 'Temporäre Aussetzung wegen gesundheitlicher Probleme.',
    },
    entziehung: {
      datum: new Date('2024-01-01'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: true,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: true,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: true,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: true,
      ausscheidenUnternehmen: true,
      sontiges: 'Entziehung wegen schwerwiegender Verstöße.',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2023-01-01'),
        naechsteUntersuchung: new Date('2024-01-01'),
        hinweise: 'Keine besonderen Hinweise.',
      },
      smsSchulung: {
        letzteSchulung: new Date('2022-01-01'),
        naechsteSchulung: new Date('2023-01-01'),
      },
    },
    sprachkenntnisse: [
      {
        bezeichnung: 'Englisch',
        erwerb: new Date('2005-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: 'Fließend in Wort und Schrift',
      },
      {
        bezeichnung: 'Spanisch',
        erwerb: new Date('2010-01-01'),
        letzteUeberpruefung: new Date('2023-06-01'),
        naechsteUeberpruefung: new Date('2024-06-01'),
        hinweise: 'Grundkenntnisse',
      },
    ],
    fahrzeugkenntnisse: [
      {
        bezeichnung: 'LKW',
        erwerb: new Date('2015-01-01'),
        letzteUeberpruefung: new Date('2023-05-01'),
        naechsteUeberpruefung: new Date('2024-05-01'),
        hinweise: 'Erforderliche Schulungen abgeschlossen',
      },
      {
        bezeichnung: 'PKW',
        erwerb: new Date('2008-01-01'),
        letzteUeberpruefung: new Date('2022-12-01'),
        naechsteUeberpruefung: new Date('2023-12-01'),
        hinweise: 'Regelmäßige Wartung erforderlich',
      },
    ],
    infrastrukturkenntnisse: [
      {
        bezeichnung: 'Verkehrsmanagementsystem',
        erwerb: new Date('2018-01-01'),
        letzteUeberpruefung: new Date('2023-04-01'),
        naechsteUeberpruefung: new Date('2024-04-01'),
        hinweise: 'Erfahrung mit modernen Systemen',
      },
      {
        bezeichnung: 'Zugbeeinflussungssysteme',
        erwerb: new Date('2020-01-01'),
        letzteUeberpruefung: new Date('2023-03-01'),
        naechsteUeberpruefung: new Date('2024-03-01'),
        hinweise: 'Kenntnisse in ETCS',
      },
    ],
  },
  {
    id: 2,
    fuehrerschein: {
      fuehrerscheinNummer: '1',
      status: 'ungültig',
    },
    inhaber: {
      name: 'Müller',
      vorname: 'Anna',
      geburtstag: new Date('1985-05-15'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 1,
      status: 'abgelaufen',
      unbefristet: false,
      ausstellungsDatum: new Date('2020-01-01'),
      ablaufGueltigkeit: new Date('2021-01-01'),
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Kreisverwaltung Musterland',
      strasseUndNummer: 'Am Rathausplatz 5',
      plz: 54321,
      ort: 'Musterstadt',
      telefon: '07654-32109',
      fax: '01234-56789',
      email: 'info@kreisverwaltung-musterland.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild-anna.jpg',
      unterschrift: 'path/to/unterschrift-anna.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma Logistik AG',
      strasseUndNummer: 'Logistikweg 1',
      plz: 98765,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '01234-98765',
      fax: '01234-56789',
      email: 'info@musterfirma-logistik.de',
      unternehmensKategorie: 'Logistik',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: false,
      A1: false,
      A2: false,
      A3: false,
      A4: false,
      A5: true,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: 'Nur mit Automatikgetriebe.',
    },
    zusaetzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschraenkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    aenderung: {
      datum: new Date('2023-06-01'),
      aenderungFeld3Klasse: 'Neue Klasse hinzugefügt: C',
      aenderungFeld4Angaben: 'Wohnort geändert',
      aenderungFeld5Sprachen: 'Spanisch hinzugefügt',
      aenderungFeld6Einschraenkung: 'Sehhilfe erforderlich',
      aenderungFeld7Fahrzeug: 'Neuer Fahrzeugtyp: LKW',
      aenderungFeld8Infrastruktur: 'Neuer Infrastrukturort hinzugefügt: Berlin',
      sontiges: 'Weitere Änderungen nicht relevant.',
    },
    aussetzung: {
      von: new Date('2023-07-01'),
      bis: new Date('2023-12-31'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: false,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: false,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: false,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: false,
      sontiges: 'Temporäre Aussetzung wegen gesundheitlicher Probleme.',
    },
    entziehung: {
      datum: new Date('2024-01-01'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: true,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: true,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: true,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: true,
      ausscheidenUnternehmen: true,
      sontiges: 'Entziehung wegen schwerwiegender Verstöße.',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2022-06-01'),
        naechsteUntersuchung: new Date('2023-06-01'),
        hinweise: 'Brillenträger, Korrektionswerte beachten.',
      },
      smsSchulung: {
        letzteSchulung: new Date('2021-12-01'),
        naechsteSchulung: new Date('2022-12-01'),
      },
    },
    sprachkenntnisse: [
      {
        bezeichnung: 'Englisch',
        erwerb: new Date('2005-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: 'Fließend in Wort und Schrift',
      },
      {
        bezeichnung: 'Spanisch',
        erwerb: new Date('2010-01-01'),
        letzteUeberpruefung: new Date('2023-06-01'),
        naechsteUeberpruefung: new Date('2024-06-01'),
        hinweise: 'Grundkenntnisse',
      },
    ],
    fahrzeugkenntnisse: [
      {
        bezeichnung: 'LKW',
        erwerb: new Date('2015-01-01'),
        letzteUeberpruefung: new Date('2023-05-01'),
        naechsteUeberpruefung: new Date('2024-05-01'),
        hinweise: 'Erforderliche Schulungen abgeschlossen',
      },
      {
        bezeichnung: 'PKW',
        erwerb: new Date('2008-01-01'),
        letzteUeberpruefung: new Date('2022-12-01'),
        naechsteUeberpruefung: new Date('2023-12-01'),
        hinweise: 'Regelmäßige Wartung erforderlich',
      },
    ],
    infrastrukturkenntnisse: [
      {
        bezeichnung: 'Verkehrsmanagementsystem',
        erwerb: new Date('2018-01-01'),
        letzteUeberpruefung: new Date('2023-04-01'),
        naechsteUeberpruefung: new Date('2024-04-01'),
        hinweise: 'Erfahrung mit modernen Systemen',
      },
      {
        bezeichnung: 'Zugbeeinflussungssysteme',
        erwerb: new Date('2020-01-01'),
        letzteUeberpruefung: new Date('2023-03-01'),
        naechsteUeberpruefung: new Date('2024-03-01'),
        hinweise: 'Kenntnisse in ETCS',
      },
    ],
  },
  {
    id: 3,
    fuehrerschein: {
      fuehrerscheinNummer: '2',
      status: 'gültig',
    },
    inhaber: {
      name: 'Schmidt',
      vorname: 'Thomas',
      geburtstag: new Date('1983-09-30'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 2,
      status: 'Entwurf',
      unbefristet: false,
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Stadtverwaltung Musterstadt',
      strasseUndNummer: 'Marktplatz 7',
      plz: 12345,
      ort: 'Musterstadt',
      telefon: '04567-89012',
      fax: '01234-56789',
      email: 'info@stadtverwaltung-musterstadt.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild-thomas.jpg',
      unterschrift: 'path/to/unterschrift-thomas.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma Bau GmbH',
      strasseUndNummer: 'Baustellenweg 3',
      plz: 54321,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '09876-54321',
      fax: '01234-56789',
      email: 'info@musterfirma-bau.de',
      unternehmensKategorie: 'Bauwesen',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: true,
      A1: true,
      A2: false,
      A3: false,
      A4: false,
      A5: false,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: '',
    },
    zusaetzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschraenkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    aenderung: {
      datum: new Date('2023-06-01'),
      aenderungFeld3Klasse: 'Neue Klasse hinzugefügt: C',
      aenderungFeld4Angaben: 'Wohnort geändert',
      aenderungFeld5Sprachen: 'Spanisch hinzugefügt',
      aenderungFeld6Einschraenkung: 'Sehhilfe erforderlich',
      aenderungFeld7Fahrzeug: 'Neuer Fahrzeugtyp: LKW',
      aenderungFeld8Infrastruktur: 'Neuer Infrastrukturort hinzugefügt: Berlin',
      sontiges: 'Weitere Änderungen nicht relevant.',
    },
    aussetzung: {
      von: new Date('2023-07-01'),
      bis: new Date('2023-12-31'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: false,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: false,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: false,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: false,
      sontiges: 'Temporäre Aussetzung wegen gesundheitlicher Probleme.',
    },
    entziehung: {
      datum: new Date('2024-01-01'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: true,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: true,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: true,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: true,
      ausscheidenUnternehmen: true,
      sontiges: 'Entziehung wegen schwerwiegender Verstöße.',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2023-05-01'),
        naechsteUntersuchung: new Date('2024-05-01'),
        hinweise: '',
      },
      smsSchulung: {
        letzteSchulung: new Date('2022-03-01'),
        naechsteSchulung: new Date('2023-03-01'),
      },
    },
    sprachkenntnisse: [
      {
        bezeichnung: 'Englisch',
        erwerb: new Date('2005-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: 'Fließend in Wort und Schrift',
      },
      {
        bezeichnung: 'Spanisch',
        erwerb: new Date('2010-01-01'),
        letzteUeberpruefung: new Date('2023-06-01'),
        naechsteUeberpruefung: new Date('2024-06-01'),
        hinweise: 'Grundkenntnisse',
      },
    ],
    fahrzeugkenntnisse: [
      {
        bezeichnung: 'LKW',
        erwerb: new Date('2015-01-01'),
        letzteUeberpruefung: new Date('2023-05-01'),
        naechsteUeberpruefung: new Date('2024-05-01'),
        hinweise: 'Erforderliche Schulungen abgeschlossen',
      },
      {
        bezeichnung: 'PKW',
        erwerb: new Date('2008-01-01'),
        letzteUeberpruefung: new Date('2022-12-01'),
        naechsteUeberpruefung: new Date('2023-12-01'),
        hinweise: 'Regelmäßige Wartung erforderlich',
      },
    ],
    infrastrukturkenntnisse: [
      {
        bezeichnung: 'Verkehrsmanagementsystem',
        erwerb: new Date('2018-01-01'),
        letzteUeberpruefung: new Date('2023-04-01'),
        naechsteUeberpruefung: new Date('2024-04-01'),
        hinweise: 'Erfahrung mit modernen Systemen',
      },
      {
        bezeichnung: 'Zugbeeinflussungssysteme',
        erwerb: new Date('2020-01-01'),
        letzteUeberpruefung: new Date('2023-03-01'),
        naechsteUeberpruefung: new Date('2024-03-01'),
        hinweise: 'Kenntnisse in ETCS',
      },
    ],
  },
  {
    id: 4,
    fuehrerschein: {
      fuehrerscheinNummer: '3',
      status: 'gültig',
    },
    inhaber: {
      name: 'Mustermann',
      vorname: 'Max',
      geburtstag: new Date('1990-01-01'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 3,
      status: 'gültig',
      unbefristet: false,
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Straßenverkehrsamt Musterstadt',
      strasseUndNummer: 'Hauptstraße 1',
      plz: 12345,
      ort: 'Musterstadt',
      telefon: '01234-56789',
      fax: '01234-56789',
      email: 'info@strassenverkehrsamt-musterstadt.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild.jpg',
      unterschrift: 'path/to/unterschrift.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma GmbH',
      strasseUndNummer: 'Industriestraße 10',
      plz: 54321,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '09876-54321',
      fax: '01234-56789',
      email: 'info@musterfirma.de',
      unternehmensKategorie: 'Dienstleistungen',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: true,
      A1: false,
      A2: false,
      A3: false,
      A4: false,
      A5: false,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: '',
    },
    zusaetzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschraenkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    aenderung: {
      datum: new Date('2023-06-01'),
      aenderungFeld3Klasse: 'Neue Klasse hinzugefügt: C',
      aenderungFeld4Angaben: 'Wohnort geändert',
      aenderungFeld5Sprachen: 'Spanisch hinzugefügt',
      aenderungFeld6Einschraenkung: 'Sehhilfe erforderlich',
      aenderungFeld7Fahrzeug: 'Neuer Fahrzeugtyp: LKW',
      aenderungFeld8Infrastruktur: 'Neuer Infrastrukturort hinzugefügt: Berlin',
      sontiges: 'Weitere Änderungen nicht relevant.',
    },
    aussetzung: {
      von: new Date('2023-07-01'),
      bis: new Date('2023-12-31'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: false,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: false,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: false,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: false,
      sontiges: 'Temporäre Aussetzung wegen gesundheitlicher Probleme.',
    },
    entziehung: {
      datum: new Date('2024-01-01'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: true,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: true,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: true,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: true,
      ausscheidenUnternehmen: true,
      sontiges: 'Entziehung wegen schwerwiegender Verstöße.',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2023-01-01'),
        naechsteUntersuchung: new Date('2024-01-01'),
        hinweise: 'Keine besonderen Hinweise.',
      },
      smsSchulung: {
        letzteSchulung: new Date('2022-01-01'),
        naechsteSchulung: new Date('2023-01-01'),
      },
    },
    sprachkenntnisse: [
      {
        bezeichnung: 'Englisch',
        erwerb: new Date('2005-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: 'Fließend in Wort und Schrift',
      },
      {
        bezeichnung: 'Spanisch',
        erwerb: new Date('2010-01-01'),
        letzteUeberpruefung: new Date('2023-06-01'),
        naechsteUeberpruefung: new Date('2024-06-01'),
        hinweise: 'Grundkenntnisse',
      },
    ],
    fahrzeugkenntnisse: [
      {
        bezeichnung: 'LKW',
        erwerb: new Date('2015-01-01'),
        letzteUeberpruefung: new Date('2023-05-01'),
        naechsteUeberpruefung: new Date('2024-05-01'),
        hinweise: 'Erforderliche Schulungen abgeschlossen',
      },
      {
        bezeichnung: 'PKW',
        erwerb: new Date('2008-01-01'),
        letzteUeberpruefung: new Date('2022-12-01'),
        naechsteUeberpruefung: new Date('2023-12-01'),
        hinweise: 'Regelmäßige Wartung erforderlich',
      },
    ],
    infrastrukturkenntnisse: [
      {
        bezeichnung: 'Verkehrsmanagementsystem',
        erwerb: new Date('2018-01-01'),
        letzteUeberpruefung: new Date('2023-04-01'),
        naechsteUeberpruefung: new Date('2024-04-01'),
        hinweise: 'Erfahrung mit modernen Systemen',
      },
      {
        bezeichnung: 'Zugbeeinflussungssysteme',
        erwerb: new Date('2020-01-01'),
        letzteUeberpruefung: new Date('2023-03-01'),
        naechsteUeberpruefung: new Date('2024-03-01'),
        hinweise: 'Kenntnisse in ETCS',
      },
    ],
  },
  {
    id: 5,
    fuehrerschein: {
      fuehrerscheinNummer: '4',
      status: 'ungültig',
    },
    inhaber: {
      name: 'Müller',
      vorname: 'Anna',
      geburtstag: new Date('1985-05-15'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 4,
      status: 'abgelaufen',
      unbefristet: false,
      ausstellungsDatum: new Date('2020-01-01'),
      ablaufGueltigkeit: new Date('2021-01-01'),
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Kreisverwaltung Musterland',
      strasseUndNummer: 'Am Rathausplatz 5',
      plz: 54321,
      ort: 'Musterstadt',
      telefon: '07654-32109',
      fax: '01234-56789',
      email: 'info@kreisverwaltung-musterland.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild-anna.jpg',
      unterschrift: 'path/to/unterschrift-anna.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma Logistik AG',
      strasseUndNummer: 'Logistikweg 1',
      plz: 98765,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '01234-98765',
      fax: '01234-56789',
      email: 'info@musterfirma-logistik.de',
      unternehmensKategorie: 'Logistik',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: false,
      A1: false,
      A2: false,
      A3: false,
      A4: false,
      A5: true,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: 'Nur mit Automatikgetriebe.',
    },
    zusaetzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschraenkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    aenderung: {
      datum: new Date('2023-06-01'),
      aenderungFeld3Klasse: 'Neue Klasse hinzugefügt: C',
      aenderungFeld4Angaben: 'Wohnort geändert',
      aenderungFeld5Sprachen: 'Spanisch hinzugefügt',
      aenderungFeld6Einschraenkung: 'Sehhilfe erforderlich',
      aenderungFeld7Fahrzeug: 'Neuer Fahrzeugtyp: LKW',
      aenderungFeld8Infrastruktur: 'Neuer Infrastrukturort hinzugefügt: Berlin',
      sontiges: 'Weitere Änderungen nicht relevant.',
    },
    aussetzung: {
      von: new Date('2023-07-01'),
      bis: new Date('2023-12-31'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: false,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: false,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: false,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: false,
      sontiges: 'Temporäre Aussetzung wegen gesundheitlicher Probleme.',
    },
    entziehung: {
      datum: new Date('2024-01-01'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: true,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: true,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: true,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: true,
      ausscheidenUnternehmen: true,
      sontiges: 'Entziehung wegen schwerwiegender Verstöße.',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2022-06-01'),
        naechsteUntersuchung: new Date('2023-06-01'),
        hinweise: 'Brillenträger, Korrektionswerte beachten.',
      },
      smsSchulung: {
        letzteSchulung: new Date('2021-12-01'),
        naechsteSchulung: new Date('2022-12-01'),
      },
    },
    sprachkenntnisse: [
      {
        bezeichnung: 'Englisch',
        erwerb: new Date('2005-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: 'Fließend in Wort und Schrift',
      },
      {
        bezeichnung: 'Spanisch',
        erwerb: new Date('2010-01-01'),
        letzteUeberpruefung: new Date('2023-06-01'),
        naechsteUeberpruefung: new Date('2024-06-01'),
        hinweise: 'Grundkenntnisse',
      },
    ],
    fahrzeugkenntnisse: [
      {
        bezeichnung: 'LKW',
        erwerb: new Date('2015-01-01'),
        letzteUeberpruefung: new Date('2023-05-01'),
        naechsteUeberpruefung: new Date('2024-05-01'),
        hinweise: 'Erforderliche Schulungen abgeschlossen',
      },
      {
        bezeichnung: 'PKW',
        erwerb: new Date('2008-01-01'),
        letzteUeberpruefung: new Date('2022-12-01'),
        naechsteUeberpruefung: new Date('2023-12-01'),
        hinweise: 'Regelmäßige Wartung erforderlich',
      },
    ],
    infrastrukturkenntnisse: [
      {
        bezeichnung: 'Verkehrsmanagementsystem',
        erwerb: new Date('2018-01-01'),
        letzteUeberpruefung: new Date('2023-04-01'),
        naechsteUeberpruefung: new Date('2024-04-01'),
        hinweise: 'Erfahrung mit modernen Systemen',
      },
      {
        bezeichnung: 'Zugbeeinflussungssysteme',
        erwerb: new Date('2020-01-01'),
        letzteUeberpruefung: new Date('2023-03-01'),
        naechsteUeberpruefung: new Date('2024-03-01'),
        hinweise: 'Kenntnisse in ETCS',
      },
    ],
  },
  {
    id: 6,
    fuehrerschein: {
      fuehrerscheinNummer: '0',
      status: 'gültig',
    },
    inhaber: {
      name: 'Schmidt',
      vorname: 'Thomas',
      geburtstag: new Date('1983-09-30'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 0,
      status: 'Entwurf',
      unbefristet: false,
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Stadtverwaltung Musterstadt',
      strasseUndNummer: 'Marktplatz 7',
      plz: 12345,
      ort: 'Musterstadt',
      telefon: '04567-89012',
      fax: '01234-56789',
      email: 'info@stadtverwaltung-musterstadt.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild-thomas.jpg',
      unterschrift: 'path/to/unterschrift-thomas.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma Bau GmbH',
      strasseUndNummer: 'Baustellenweg 3',
      plz: 54321,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '09876-54321',
      fax: '01234-56789',
      email: 'info@musterfirma-bau.de',
      unternehmensKategorie: 'Bauwesen',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: true,
      A1: true,
      A2: false,
      A3: false,
      A4: false,
      A5: false,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: '',
    },
    zusaetzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschraenkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    aenderung: {
      datum: new Date('2023-06-01'),
      aenderungFeld3Klasse: 'Neue Klasse hinzugefügt: C',
      aenderungFeld4Angaben: 'Wohnort geändert',
      aenderungFeld5Sprachen: 'Spanisch hinzugefügt',
      aenderungFeld6Einschraenkung: 'Sehhilfe erforderlich',
      aenderungFeld7Fahrzeug: 'Neuer Fahrzeugtyp: LKW',
      aenderungFeld8Infrastruktur: 'Neuer Infrastrukturort hinzugefügt: Berlin',
      sontiges: 'Weitere Änderungen nicht relevant.',
    },
    aussetzung: {
      von: new Date('2023-07-01'),
      bis: new Date('2023-12-31'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: false,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: false,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: false,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: false,
      sontiges: 'Temporäre Aussetzung wegen gesundheitlicher Probleme.',
    },
    entziehung: {
      datum: new Date('2024-01-01'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: true,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: true,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: true,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: true,
      ausscheidenUnternehmen: true,
      sontiges: 'Entziehung wegen schwerwiegender Verstöße.',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2023-05-01'),
        naechsteUntersuchung: new Date('2024-05-01'),
        hinweise: '',
      },
      smsSchulung: {
        letzteSchulung: new Date('2022-03-01'),
        naechsteSchulung: new Date('2023-03-01'),
      },
    },
    sprachkenntnisse: [
      {
        bezeichnung: 'Englisch',
        erwerb: new Date('2005-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: 'Fließend in Wort und Schrift',
      },
      {
        bezeichnung: 'Spanisch',
        erwerb: new Date('2010-01-01'),
        letzteUeberpruefung: new Date('2023-06-01'),
        naechsteUeberpruefung: new Date('2024-06-01'),
        hinweise: 'Grundkenntnisse',
      },
    ],
    fahrzeugkenntnisse: [
      {
        bezeichnung: 'LKW',
        erwerb: new Date('2015-01-01'),
        letzteUeberpruefung: new Date('2023-05-01'),
        naechsteUeberpruefung: new Date('2024-05-01'),
        hinweise: 'Erforderliche Schulungen abgeschlossen',
      },
      {
        bezeichnung: 'PKW',
        erwerb: new Date('2008-01-01'),
        letzteUeberpruefung: new Date('2022-12-01'),
        naechsteUeberpruefung: new Date('2023-12-01'),
        hinweise: 'Regelmäßige Wartung erforderlich',
      },
    ],
    infrastrukturkenntnisse: [
      {
        bezeichnung: 'Verkehrsmanagementsystem',
        erwerb: new Date('2018-01-01'),
        letzteUeberpruefung: new Date('2023-04-01'),
        naechsteUeberpruefung: new Date('2024-04-01'),
        hinweise: 'Erfahrung mit modernen Systemen',
      },
      {
        bezeichnung: 'Zugbeeinflussungssysteme',
        erwerb: new Date('2020-01-01'),
        letzteUeberpruefung: new Date('2023-03-01'),
        naechsteUeberpruefung: new Date('2024-03-01'),
        hinweise: 'Kenntnisse in ETCS',
      },
    ],
  },
  {
    id: 7,
    fuehrerschein: {
      fuehrerscheinNummer: '1',
      status: 'gültig',
    },
    inhaber: {
      name: 'Mustermann',
      vorname: 'Max',
      geburtstag: new Date('1990-01-01'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 1,
      status: 'gültig',
      unbefristet: false,
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Straßenverkehrsamt Musterstadt',
      strasseUndNummer: 'Hauptstraße 1',
      plz: 12345,
      ort: 'Musterstadt',
      telefon: '01234-56789',
      fax: '01234-56789',
      email: 'info@strassenverkehrsamt-musterstadt.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild.jpg',
      unterschrift: 'path/to/unterschrift.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma GmbH',
      strasseUndNummer: 'Industriestraße 10',
      plz: 54321,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '09876-54321',
      fax: '01234-56789',
      email: 'info@musterfirma.de',
      unternehmensKategorie: 'Dienstleistungen',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: true,
      A1: false,
      A2: false,
      A3: false,
      A4: false,
      A5: false,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: '',
    },
    zusaetzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschraenkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    aenderung: {
      datum: new Date('2023-06-01'),
      aenderungFeld3Klasse: 'Neue Klasse hinzugefügt: C',
      aenderungFeld4Angaben: 'Wohnort geändert',
      aenderungFeld5Sprachen: 'Spanisch hinzugefügt',
      aenderungFeld6Einschraenkung: 'Sehhilfe erforderlich',
      aenderungFeld7Fahrzeug: 'Neuer Fahrzeugtyp: LKW',
      aenderungFeld8Infrastruktur: 'Neuer Infrastrukturort hinzugefügt: Berlin',
      sontiges: 'Weitere Änderungen nicht relevant.',
    },
    aussetzung: {
      von: new Date('2023-07-01'),
      bis: new Date('2023-12-31'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: false,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: false,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: false,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: false,
      sontiges: 'Temporäre Aussetzung wegen gesundheitlicher Probleme.',
    },
    entziehung: {
      datum: new Date('2024-01-01'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: true,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: true,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: true,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: true,
      ausscheidenUnternehmen: true,
      sontiges: 'Entziehung wegen schwerwiegender Verstöße.',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2023-01-01'),
        naechsteUntersuchung: new Date('2024-01-01'),
        hinweise: 'Keine besonderen Hinweise.',
      },
      smsSchulung: {
        letzteSchulung: new Date('2022-01-01'),
        naechsteSchulung: new Date('2023-01-01'),
      },
    },
    sprachkenntnisse: [
      {
        bezeichnung: 'Englisch',
        erwerb: new Date('2005-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: 'Fließend in Wort und Schrift',
      },
      {
        bezeichnung: 'Spanisch',
        erwerb: new Date('2010-01-01'),
        letzteUeberpruefung: new Date('2023-06-01'),
        naechsteUeberpruefung: new Date('2024-06-01'),
        hinweise: 'Grundkenntnisse',
      },
    ],
    fahrzeugkenntnisse: [
      {
        bezeichnung: 'LKW',
        erwerb: new Date('2015-01-01'),
        letzteUeberpruefung: new Date('2023-05-01'),
        naechsteUeberpruefung: new Date('2024-05-01'),
        hinweise: 'Erforderliche Schulungen abgeschlossen',
      },
      {
        bezeichnung: 'PKW',
        erwerb: new Date('2008-01-01'),
        letzteUeberpruefung: new Date('2022-12-01'),
        naechsteUeberpruefung: new Date('2023-12-01'),
        hinweise: 'Regelmäßige Wartung erforderlich',
      },
    ],
    infrastrukturkenntnisse: [
      {
        bezeichnung: 'Verkehrsmanagementsystem',
        erwerb: new Date('2018-01-01'),
        letzteUeberpruefung: new Date('2023-04-01'),
        naechsteUeberpruefung: new Date('2024-04-01'),
        hinweise: 'Erfahrung mit modernen Systemen',
      },
      {
        bezeichnung: 'Zugbeeinflussungssysteme',
        erwerb: new Date('2020-01-01'),
        letzteUeberpruefung: new Date('2023-03-01'),
        naechsteUeberpruefung: new Date('2024-03-01'),
        hinweise: 'Kenntnisse in ETCS',
      },
    ],
  },
  {
    id: 8,
    fuehrerschein: {
      fuehrerscheinNummer: '2',
      status: 'ungültig',
    },
    inhaber: {
      name: 'Müller',
      vorname: 'Anna',
      geburtstag: new Date('1985-05-15'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 2,
      status: 'abgelaufen',
      unbefristet: false,
      ausstellungsDatum: new Date('2020-01-01'),
      ablaufGueltigkeit: new Date('2021-01-01'),
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Kreisverwaltung Musterland',
      strasseUndNummer: 'Am Rathausplatz 5',
      plz: 54321,
      ort: 'Musterstadt',
      telefon: '07654-32109',
      fax: '01234-56789',
      email: 'info@kreisverwaltung-musterland.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild-anna.jpg',
      unterschrift: 'path/to/unterschrift-anna.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma Logistik AG',
      strasseUndNummer: 'Logistikweg 1',
      plz: 98765,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '01234-98765',
      fax: '01234-56789',
      email: 'info@musterfirma-logistik.de',
      unternehmensKategorie: 'Logistik',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: false,
      A1: false,
      A2: false,
      A3: false,
      A4: false,
      A5: true,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: 'Nur mit Automatikgetriebe.',
    },
    zusaetzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschraenkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    aenderung: {
      datum: new Date('2023-06-01'),
      aenderungFeld3Klasse: 'Neue Klasse hinzugefügt: C',
      aenderungFeld4Angaben: 'Wohnort geändert',
      aenderungFeld5Sprachen: 'Spanisch hinzugefügt',
      aenderungFeld6Einschraenkung: 'Sehhilfe erforderlich',
      aenderungFeld7Fahrzeug: 'Neuer Fahrzeugtyp: LKW',
      aenderungFeld8Infrastruktur: 'Neuer Infrastrukturort hinzugefügt: Berlin',
      sontiges: 'Weitere Änderungen nicht relevant.',
    },
    aussetzung: {
      von: new Date('2023-07-01'),
      bis: new Date('2023-12-31'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: false,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: false,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: false,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: false,
      sontiges: 'Temporäre Aussetzung wegen gesundheitlicher Probleme.',
    },
    entziehung: {
      datum: new Date('2024-01-01'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: true,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: true,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: true,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: true,
      ausscheidenUnternehmen: true,
      sontiges: 'Entziehung wegen schwerwiegender Verstöße.',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2022-06-01'),
        naechsteUntersuchung: new Date('2023-06-01'),
        hinweise: 'Brillenträger, Korrektionswerte beachten.',
      },
      smsSchulung: {
        letzteSchulung: new Date('2021-12-01'),
        naechsteSchulung: new Date('2022-12-01'),
      },
    },
    sprachkenntnisse: [
      {
        bezeichnung: 'Englisch',
        erwerb: new Date('2005-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: 'Fließend in Wort und Schrift',
      },
      {
        bezeichnung: 'Spanisch',
        erwerb: new Date('2010-01-01'),
        letzteUeberpruefung: new Date('2023-06-01'),
        naechsteUeberpruefung: new Date('2024-06-01'),
        hinweise: 'Grundkenntnisse',
      },
    ],
    fahrzeugkenntnisse: [
      {
        bezeichnung: 'LKW',
        erwerb: new Date('2015-01-01'),
        letzteUeberpruefung: new Date('2023-05-01'),
        naechsteUeberpruefung: new Date('2024-05-01'),
        hinweise: 'Erforderliche Schulungen abgeschlossen',
      },
      {
        bezeichnung: 'PKW',
        erwerb: new Date('2008-01-01'),
        letzteUeberpruefung: new Date('2022-12-01'),
        naechsteUeberpruefung: new Date('2023-12-01'),
        hinweise: 'Regelmäßige Wartung erforderlich',
      },
    ],
    infrastrukturkenntnisse: [
      {
        bezeichnung: 'Verkehrsmanagementsystem',
        erwerb: new Date('2018-01-01'),
        letzteUeberpruefung: new Date('2023-04-01'),
        naechsteUeberpruefung: new Date('2024-04-01'),
        hinweise: 'Erfahrung mit modernen Systemen',
      },
      {
        bezeichnung: 'Zugbeeinflussungssysteme',
        erwerb: new Date('2020-01-01'),
        letzteUeberpruefung: new Date('2023-03-01'),
        naechsteUeberpruefung: new Date('2024-03-01'),
        hinweise: 'Kenntnisse in ETCS',
      },
    ],
  },
  {
    id: 9,
    fuehrerschein: {
      fuehrerscheinNummer: '3',
      status: 'gültig',
    },
    inhaber: {
      name: 'Schmidt',
      vorname: 'Thomas',
      geburtstag: new Date('1983-09-30'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 3,
      status: 'Entwurf',
      unbefristet: false,
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Stadtverwaltung Musterstadt',
      strasseUndNummer: 'Marktplatz 7',
      plz: 12345,
      ort: 'Musterstadt',
      telefon: '04567-89012',
      fax: '01234-56789',
      email: 'info@stadtverwaltung-musterstadt.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild-thomas.jpg',
      unterschrift: 'path/to/unterschrift-thomas.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma Bau GmbH',
      strasseUndNummer: 'Baustellenweg 3',
      plz: 54321,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '09876-54321',
      fax: '01234-56789',
      email: 'info@musterfirma-bau.de',
      unternehmensKategorie: 'Bauwesen',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: true,
      A1: true,
      A2: false,
      A3: false,
      A4: false,
      A5: false,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: '',
    },
    zusaetzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschraenkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    aenderung: {
      datum: new Date('2023-06-01'),
      aenderungFeld3Klasse: 'Neue Klasse hinzugefügt: C',
      aenderungFeld4Angaben: 'Wohnort geändert',
      aenderungFeld5Sprachen: 'Spanisch hinzugefügt',
      aenderungFeld6Einschraenkung: 'Sehhilfe erforderlich',
      aenderungFeld7Fahrzeug: 'Neuer Fahrzeugtyp: LKW',
      aenderungFeld8Infrastruktur: 'Neuer Infrastrukturort hinzugefügt: Berlin',
      sontiges: 'Weitere Änderungen nicht relevant.',
    },
    aussetzung: {
      von: new Date('2023-07-01'),
      bis: new Date('2023-12-31'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: false,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: false,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: false,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: false,
      sontiges: 'Temporäre Aussetzung wegen gesundheitlicher Probleme.',
    },
    entziehung: {
      datum: new Date('2024-01-01'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: true,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: true,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: true,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: true,
      ausscheidenUnternehmen: true,
      sontiges: 'Entziehung wegen schwerwiegender Verstöße.',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2023-05-01'),
        naechsteUntersuchung: new Date('2024-05-01'),
        hinweise: '',
      },
      smsSchulung: {
        letzteSchulung: new Date('2022-03-01'),
        naechsteSchulung: new Date('2023-03-01'),
      },
    },
    sprachkenntnisse: [
      {
        bezeichnung: 'Englisch',
        erwerb: new Date('2005-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: 'Fließend in Wort und Schrift',
      },
      {
        bezeichnung: 'Spanisch',
        erwerb: new Date('2010-01-01'),
        letzteUeberpruefung: new Date('2023-06-01'),
        naechsteUeberpruefung: new Date('2024-06-01'),
        hinweise: 'Grundkenntnisse',
      },
    ],
    fahrzeugkenntnisse: [
      {
        bezeichnung: 'LKW',
        erwerb: new Date('2015-01-01'),
        letzteUeberpruefung: new Date('2023-05-01'),
        naechsteUeberpruefung: new Date('2024-05-01'),
        hinweise: 'Erforderliche Schulungen abgeschlossen',
      },
      {
        bezeichnung: 'PKW',
        erwerb: new Date('2008-01-01'),
        letzteUeberpruefung: new Date('2022-12-01'),
        naechsteUeberpruefung: new Date('2023-12-01'),
        hinweise: 'Regelmäßige Wartung erforderlich',
      },
    ],
    infrastrukturkenntnisse: [
      {
        bezeichnung: 'Verkehrsmanagementsystem',
        erwerb: new Date('2018-01-01'),
        letzteUeberpruefung: new Date('2023-04-01'),
        naechsteUeberpruefung: new Date('2024-04-01'),
        hinweise: 'Erfahrung mit modernen Systemen',
      },
      {
        bezeichnung: 'Zugbeeinflussungssysteme',
        erwerb: new Date('2020-01-01'),
        letzteUeberpruefung: new Date('2023-03-01'),
        naechsteUeberpruefung: new Date('2024-03-01'),
        hinweise: 'Kenntnisse in ETCS',
      },
    ],
  },
]
