import { Vehicle, Person, Infrastructure, Language } from '../types/types'

export const vehicle: Vehicle[] = [
  { id: 1, value: '111', clusterA: 'E', clusterB: 'EA' },
  { id: 2, value: '143', clusterA: 'E', clusterB: 'EA' },
  { id: 3, value: '112', clusterA: 'E', clusterB: 'EA' },
  { id: 4, value: '110', clusterA: 'E', clusterB: 'EA' },
  { id: 5, value: '48X Stwg.', clusterA: '', clusterB: 'Stwg' },
  { id: 6, value: '201-204', clusterA: 'V', clusterB: 'VS' },
  { id: 7, value: '211-213', clusterA: 'V', clusterB: 'VS' },
  { id: 8, value: 'SF03 FFS', clusterA: 'V', clusterB: 'Nfz' },
  { id: 9, value: 'BRX MTW', clusterA: 'V', clusterB: 'Nfz' },
  { id: 10, value: 'G1000', clusterA: 'V', clusterB: 'VS' },
  { id: 11, value: '114', clusterA: 'E', clusterB: 'EA' },
  { id: 12, value: '218', clusterA: 'V', clusterB: 'VS' },
  { id: 13, value: 'SKL Klv 53', clusterA: 'V', clusterB: 'Nfz' },
  { id: 14, value: '232/234', clusterA: 'V', clusterB: 'VS' },
  { id: 15, value: '360', clusterA: 'V', clusterB: 'VR' },
  { id: 16, value: '181', clusterA: 'E', clusterB: 'EA' },
  { id: 17, value: '120', clusterA: 'E', clusterB: 'ED' },
  { id: 18, value: 'Dampf (Kohle)', clusterA: 'D', clusterB: 'D' },
  { id: 19, value: '346', clusterA: 'V', clusterB: 'VR' },
  { id: 20, value: '185', clusterA: 'E', clusterB: 'ED' },
  { id: 21, value: '650', clusterA: 'V', clusterB: 'VT' },
  { id: 22, value: 'V118', clusterA: 'D', clusterB: 'VS' },
  { id: 23, value: '1648', clusterA: 'V', clusterB: 'VT' },
  { id: 24, value: 'E159', clusterA: 'E', clusterB: 'ED' },
  { id: 25, value: '109', clusterA: 'E', clusterB: 'EA' },
  { id: 26, value: '216', clusterA: 'D', clusterB: 'VS' },
  { id: 27, value: '626/926', clusterA: 'V', clusterB: 'VT' },
  { id: 28, value: 'SF 02', clusterA: 'V', clusterB: 'Nfz' },
  { id: 29, value: 'Skl Klv 26', clusterA: 'V', clusterB: 'Nfz' },
  { id: 30, value: '686', clusterA: 'V', clusterB: 'VT' },
  { id: 31, value: 'BW 04', clusterA: 'V', clusterB: 'Nfz' },
  { id: 32, value: '381', clusterA: 'V', clusterB: 'VR' },
  { id: 33, value: '183', clusterA: 'E', clusterB: 'ED' },
  { id: 34, value: 'G1206', clusterA: 'V', clusterB: 'VS' },
  { id: 35, value: '225', clusterA: '', clusterB: 'VS' },
  { id: 36, value: 'V159', clusterA: 'V', clusterB: 'VS' },
  { id: 37, value: '228', clusterA: 'D', clusterB: 'VS' },
  { id: 38, value: '293', clusterA: 'V', clusterB: 'VR' },
  { id: 39, value: '189', clusterA: '', clusterB: 'ED' },
  { id: 40, value: '230', clusterA: '', clusterB: 'VS' },
  { id: 41, value: '214', clusterA: '', clusterB: 'VS' },
  { id: 42, value: '101', clusterA: '', clusterB: 'ED' },
  { id: 43, value: '186', clusterA: '', clusterB: 'ED' },
  { id: 44, value: 'DE2400', clusterA: 'V', clusterB: '' },
  { id: 45, value: '193', clusterA: '', clusterB: 'ED' },
  { id: 46, value: '140', clusterA: '', clusterB: 'EA' },
  { id: 47, value: '146,1', clusterA: '', clusterB: 'ED' },
  { id: 48, value: '362/363', clusterA: '', clusterB: 'VS' },
  // { id: 49, value: '628', clusterA: '', clusterB: 'VT' },
  { id: 50, value: '229', clusterA: '', clusterB: 'VR' },
  { id: 51, value: '271-296', clusterA: '', clusterB: 'VS' },
  { id: 52, value: 'Dampf (Öl)', clusterA: '', clusterB: 'D' },
  { id: 53, value: '628', clusterA: 'V', clusterB: 'VT' },
  { id: 54, value: '642', clusterA: 'V', clusterB: 'VT' },
  { id: 55, value: '798/998', clusterA: 'V', clusterB: 'VT' },
  { id: 56, value: '512/KM 1200BB', clusterA: 'V', clusterB: 'VR' },
  { id: 57, value: '401', clusterA: 'E', clusterB: 'ICE' },
  { id: 58, value: '402', clusterA: 'E', clusterB: 'ICE' },
  { id: 59, value: '403', clusterA: 'E', clusterB: 'ICE' },
  { id: 60, value: '772', clusterA: 'V', clusterB: 'VT' },
  { id: 61, value: 'V162', clusterA: 'V', clusterB: 'VS' },
  { id: 62, value: '422', clusterA: 'E', clusterB: 'ET' },
  { id: 63, value: '442', clusterA: 'E', clusterB: 'ET' },
  { id: 64, value: '261', clusterA: 'V', clusterB: 'VR' },
  { id: 65, value: '295', clusterA: 'D', clusterB: 'VT' },
  { id: 66, value: 'GAF 100', clusterA: 'D', clusterB: 'D' },
  { id: 67, value: '462', clusterA: 'E', clusterB: 'VT' },
]

export const infrastructure: Infrastructure[] = [
  { id: 1, value: 'FV-DB' },
  { id: 2, value: 'FV-NE' },
  { id: 3, value: 'ZLB' },
  { id: 4, value: 'SZB' },
  { id: 5, value: 'Steilstreckenbetrieb' },
  { id: 6, value: 'PZB' },
  { id: 7, value: 'LZB' },
  { id: 8, value: 'LZB CE' },
  { id: 9, value: 'GNT' },
  { id: 10, value: 'FFB' },
  { id: 11, value: 'ETCS Stufe 1' },
  { id: 12, value: 'ETCS Stufe 2' },
  { id: 13, value: 'ETCS Stufe 3' },
  { id: 14, value: 'ZBS' },
  { id: 15, value: 'H/V' },
  { id: 16, value: 'Hl' },
  { id: 17, value: 'Ks' },
  { id: 18, value: 'Sv' },
  { id: 19, value: 'Sk' },
]

export const languages: Language[] = [
  { id: 1, value: 'Deutsch' },
  { id: 2, value: 'Englisch' },
  { id: 3, value: 'Französisch' },
  { id: 4, value: 'Spanisch' },
  { id: 5, value: 'Italienisch' },
  { id: 6, value: 'Niederländisch' },
  { id: 7, value: 'Portugiesisch' },
  { id: 8, value: 'Russisch' },
  { id: 9, value: 'Chinesisch' },
  { id: 10, value: 'Japanisch' },
  { id: 11, value: 'Koreanisch' },
  { id: 12, value: 'Arabisch' },
  { id: 13, value: 'Türkisch' },
  { id: 14, value: 'Hindi' },
  { id: 15, value: 'Bengalisch' },
  { id: 16, value: 'Punjabi' },
  { id: 17, value: 'Urdu' },
  { id: 18, value: 'Vietnamesisch' },
  { id: 19, value: 'Persisch' },
  { id: 20, value: 'Thai' },
  { id: 21, value: 'Griechisch' },
  { id: 22, value: 'Schwedisch' },
  { id: 23, value: 'Norwegisch' },
  { id: 24, value: 'Dänisch' },
  { id: 25, value: 'Finnisch' },
  { id: 26, value: 'Ungarisch' },
  { id: 27, value: 'Tschechisch' },
  { id: 28, value: 'Slowakisch' },
  { id: 29, value: 'Polnisch' },
  { id: 30, value: 'Rumänisch' },
  { id: 31, value: 'Bulgarisch' },
  { id: 32, value: 'Serbisch' },
  { id: 33, value: 'Kroatisch' },
  { id: 34, value: 'Slowenisch' },
  { id: 35, value: 'Litauisch' },
  { id: 36, value: 'Lettisch' },
  { id: 37, value: 'Estnisch' },
  { id: 38, value: 'Maltesisch' },
  { id: 39, value: 'Isländisch' },
  { id: 40, value: 'Irisch' },
  { id: 41, value: 'Walisisch' },
  { id: 42, value: 'Schottisch-Gälisch' },
  { id: 43, value: 'Hebräisch' },
  { id: 44, value: 'Jiddisch' },
  { id: 45, value: 'Afrikaans' },
  { id: 46, value: 'Swahili' },
  { id: 47, value: 'Zulu' },
  { id: 48, value: 'Xhosa' },
  { id: 49, value: 'Igbo' },
  { id: 50, value: 'Yoruba' },
  { id: 51, value: 'Hausa' },
  { id: 52, value: 'Amharisch' },
  { id: 53, value: 'Somali' },
  { id: 54, value: 'Madagassisch' },
]

export const fakeData: Person[] = [
  {
    id: 1,
    fuehrerschein: {
      fuehrerscheinNummer: 'DE1234567890',
      status: 'gültig',
    },
    inhaber: {
      name: 'Mustermann',
      vorname: 'Max',
      geburtstag: new Date('1990-01-01'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 1,
      status: 'gültig',
      ausstellungsDatum: new Date('2024-01-01'),
      ablaufGueltigkeit: new Date('2027-01-01'),
      unbefristet: false,
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Straßenverkehrsamt Musterstadt',
      strasseUndNummer: 'Hauptstraße 1',
      plz: 12345,
      ort: 'Musterstadt',
      telefon: '01234-56789',
      fax: '01234-56789',
      email: 'info@strassenverkehrsamt-musterstadt.de',
    },
    bilder: {
      lichtBild: '',
      unterschrift: '',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma GmbH',
      strasseUndNummer: 'Industriestraße 10',
      plz: 54321,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '09876-54321',
      fax: '01234-56789',
      email: 'info@musterfirma.de',
      unternehmensKategorie: 'Verkehrsunternehmen',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: true,
      A1: false,
      A2: false,
      A3: false,
      A4: false,
      A5: false,
      B: false,
      B1: false,
      B2: true,
      hinweiseKlasseA5: 'Ich bin ein Hinweis',
    },
    zusaetzlicheAngaben: {
      zelle1: 'ich hab',
      zelle2: 'garnix',
      zelle3: 'gemacht',
    },
    einschraenkungen: {
      zelle1: 'blind',
      zelle2: 'behindert',
      zelle3: '24cm',
    },
    aenderung: {
      datum: new Date('2023-06-01'),
      aenderungFeld3Klasse: 'Neue Klasse hinzugefügt: C',
      aenderungFeld4Angaben: 'Wohnort geändert',
      aenderungFeld5Sprachen: 'Spanisch hinzugefügt',
      aenderungFeld6Einschraenkung: 'Sehhilfe erforderlich',
      aenderungFeld7Fahrzeug: 'Neuer Fahrzeugtyp: LKW',
      aenderungFeld8Infrastruktur: 'Neuer Infrastrukturort hinzugefügt: Berlin',
      sontiges: 'Weitere Änderungen nicht relevant.',
    },
    aussetzung: {
      von: new Date('2023-07-01'),
      bis: new Date('2023-12-31'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: false,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: false,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: false,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: false,
      sontiges: 'Temporäre Aussetzung wegen gesundheitlicher Probleme.',
    },
    entziehung: {
      datum: new Date('2024-01-01'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: true,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: true,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: true,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: true,
      ausscheidenUnternehmen: true,
      sontiges: 'Entziehung wegen schwerwiegender Verstöße.',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2023-01-01'),
        naechsteUntersuchung: new Date('2024-01-01'),
        hinweise: 'Keine besonderen Hinweise.',
      },
      smsSchulung: {
        letzteSchulung: new Date('2022-01-01'),
        naechsteSchulung: new Date('2023-01-01'),
      },
    },
    sprachkenntnisse: [
      {
        bezeichnung: 'Englisch',
        erwerb: new Date('2005-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: 'Fließend in Wort und Schrift',
      },
      {
        bezeichnung: 'Spanisch',
        erwerb: new Date('2010-01-01'),
        letzteUeberpruefung: new Date('2023-06-01'),
        naechsteUeberpruefung: new Date('2024-06-01'),
        hinweise: 'Grundkenntnisse',
      },
    ],
    fahrzeugkenntnisse: [
      {
        bezeichnung: 'LKW',
        erwerb: new Date('2015-01-01'),
        letzteUeberpruefung: new Date('2023-05-01'),
        naechsteUeberpruefung: new Date('2024-05-01'),
        hinweise: 'Erforderliche Schulungen abgeschlossen',
      },
      {
        bezeichnung: 'PKW',
        erwerb: new Date('2008-01-01'),
        letzteUeberpruefung: new Date('2022-12-01'),
        naechsteUeberpruefung: new Date('2023-12-01'),
        hinweise: 'Regelmäßige Wartung erforderlich',
      },
    ],
    infrastrukturkenntnisse: [
      {
        bezeichnung: 'Verkehrsmanagementsystem',
        erwerb: new Date('2018-01-01'),
        letzteUeberpruefung: new Date('2023-04-01'),
        naechsteUeberpruefung: new Date('2024-04-01'),
        hinweise: 'Erfahrung mit modernen Systemen',
      },
      {
        bezeichnung: 'Zugbeeinflussungssysteme',
        erwerb: new Date('2020-01-01'),
        letzteUeberpruefung: new Date('2023-03-01'),
        naechsteUeberpruefung: new Date('2024-03-01'),
        hinweise: 'Kenntnisse in ETCS',
      },
    ],
  },
  {
    id: 2,
    fuehrerschein: {
      fuehrerscheinNummer: 'DE1234567890',
      status: 'gültig',
    },
    inhaber: {
      name: 'Müller',
      vorname: 'Anna',
      geburtstag: new Date('1985-05-15'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 2,
      status: 'gültig',
      unbefristet: false,
      ausstellungsDatum: new Date('2020-01-01'),
      ablaufGueltigkeit: new Date('2021-01-01'),
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Kreisverwaltung Musterland',
      strasseUndNummer: 'Am Rathausplatz 5',
      plz: 54321,
      ort: 'Musterstadt',
      telefon: '07654-32109',
      fax: '01234-56789',
      email: 'info@kreisverwaltung-musterland.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild-anna.jpg',
      unterschrift: 'path/to/unterschrift-anna.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma Logistik AG',
      strasseUndNummer: 'Logistikweg 1',
      plz: 98765,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '01234-98765',
      fax: '01234-56789',
      email: 'info@musterfirma-logistik.de',
      unternehmensKategorie: 'Verkehrsunternehmen',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: false,
      A1: false,
      A2: false,
      A3: false,
      A4: false,
      A5: true,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: 'Nur mit Automatikgetriebe.',
    },
    zusaetzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschraenkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    aenderung: {
      datum: new Date('2023-06-01'),
      aenderungFeld3Klasse: 'Neue Klasse hinzugefügt: C',
      aenderungFeld4Angaben: 'Wohnort geändert',
      aenderungFeld5Sprachen: 'Spanisch hinzugefügt',
      aenderungFeld6Einschraenkung: 'Sehhilfe erforderlich',
      aenderungFeld7Fahrzeug: 'Neuer Fahrzeugtyp: LKW',
      aenderungFeld8Infrastruktur: 'Neuer Infrastrukturort hinzugefügt: Berlin',
      sontiges: 'Weitere Änderungen nicht relevant.',
    },
    aussetzung: {
      von: new Date('2023-07-01'),
      bis: new Date('2023-12-31'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: false,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: false,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: false,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: false,
      sontiges: 'Temporäre Aussetzung wegen gesundheitlicher Probleme.',
    },
    entziehung: {
      datum: new Date('2024-01-01'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: true,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: true,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: true,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: true,
      ausscheidenUnternehmen: true,
      sontiges: 'Entziehung wegen schwerwiegender Verstöße.',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2022-06-01'),
        naechsteUntersuchung: new Date('2023-06-01'),
        hinweise: 'Brillenträger, Korrektionswerte beachten.',
      },
      smsSchulung: {
        letzteSchulung: new Date('2021-12-01'),
        naechsteSchulung: new Date('2022-12-01'),
      },
    },
    sprachkenntnisse: [
      // {
      //   bezeichnung: 'Englisch',
      //   erwerb: new Date('2005-01-01'),
      //   letzteUeberpruefung: new Date('2023-01-01'),
      //   naechsteUeberpruefung: new Date('2024-01-01'),
      //   hinweise: 'Fließend in Wort und Schrift',
      // },
      // {
      //   bezeichnung: 'Spanisch',
      //   erwerb: new Date('2010-01-01'),
      //   letzteUeberpruefung: new Date('2023-06-01'),
      //   naechsteUeberpruefung: new Date('2024-06-01'),
      //   hinweise: 'Grundkenntnisse',
      // },
    ],
    fahrzeugkenntnisse: [
      // {
      //   bezeichnung: 'LKW',
      //   erwerb: new Date('2015-01-01'),
      //   letzteUeberpruefung: new Date('2023-05-01'),
      //   naechsteUeberpruefung: new Date('2024-05-01'),
      //   hinweise: 'Erforderliche Schulungen abgeschlossen',
      // },
      // {
      //   bezeichnung: 'PKW',
      //   erwerb: new Date('2008-01-01'),
      //   letzteUeberpruefung: new Date('2022-12-01'),
      //   naechsteUeberpruefung: new Date('2023-12-01'),
      //   hinweise: 'Regelmäßige Wartung erforderlich',
      // },
    ],
    infrastrukturkenntnisse: [
      // {
      //   bezeichnung: 'Verkehrsmanagementsystem',
      //   erwerb: new Date('2018-01-01'),
      //   letzteUeberpruefung: new Date('2023-04-01'),
      //   naechsteUeberpruefung: new Date('2024-04-01'),
      //   hinweise: 'Erfahrung mit modernen Systemen',
      // },
      // {
      //   bezeichnung: 'Zugbeeinflussungssysteme',
      //   erwerb: new Date('2020-01-01'),
      //   letzteUeberpruefung: new Date('2023-03-01'),
      //   naechsteUeberpruefung: new Date('2024-03-01'),
      //   hinweise: 'Kenntnisse in ETCS',
      // },
    ],
  },
  {
    id: 3,
    fuehrerschein: {
      fuehrerscheinNummer: 'DE1234567890',
      status: 'gültig',
    },
    inhaber: {
      name: 'Schmidt',
      vorname: 'Thomas',
      geburtstag: new Date('1983-09-30'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 3,
      status: 'Entwurf',
      unbefristet: false,
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Stadtverwaltung Musterstadt',
      strasseUndNummer: 'Marktplatz 7',
      plz: 12345,
      ort: 'Musterstadt',
      telefon: '04567-89012',
      fax: '01234-56789',
      email: 'info@stadtverwaltung-musterstadt.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild-thomas.jpg',
      unterschrift: 'path/to/unterschrift-thomas.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma Bau GmbH',
      strasseUndNummer: 'Baustellenweg 3',
      plz: 54321,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '09876-54321',
      fax: '01234-56789',
      email: 'info@musterfirma-bau.de',
      unternehmensKategorie: 'Verkehrsunternehmen',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: true,
      A1: true,
      A2: false,
      A3: false,
      A4: false,
      A5: false,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: '',
    },
    zusaetzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschraenkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    aenderung: {
      datum: new Date('2023-06-01'),
      aenderungFeld3Klasse: 'Neue Klasse hinzugefügt: C',
      aenderungFeld4Angaben: 'Wohnort geändert',
      aenderungFeld5Sprachen: 'Spanisch hinzugefügt',
      aenderungFeld6Einschraenkung: 'Sehhilfe erforderlich',
      aenderungFeld7Fahrzeug: 'Neuer Fahrzeugtyp: LKW',
      aenderungFeld8Infrastruktur: 'Neuer Infrastrukturort hinzugefügt: Berlin',
      sontiges: 'Weitere Änderungen nicht relevant.',
    },
    aussetzung: {
      von: new Date('2023-07-01'),
      bis: new Date('2023-12-31'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: false,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: false,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: false,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: false,
      sontiges: 'Temporäre Aussetzung wegen gesundheitlicher Probleme.',
    },
    entziehung: {
      datum: new Date('2024-01-01'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: true,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: true,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: true,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: true,
      ausscheidenUnternehmen: true,
      sontiges: 'Entziehung wegen schwerwiegender Verstöße.',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2023-05-01'),
        naechsteUntersuchung: new Date('2024-05-01'),
        hinweise: '',
      },
      smsSchulung: {
        letzteSchulung: new Date('2022-03-01'),
        naechsteSchulung: new Date('2023-03-01'),
      },
    },
    sprachkenntnisse: [
      {
        bezeichnung: 'Englisch',
        erwerb: new Date('2005-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: 'Fließend in Wort und Schrift',
      },
      {
        bezeichnung: 'Spanisch',
        erwerb: new Date('2010-01-01'),
        letzteUeberpruefung: new Date('2023-06-01'),
        naechsteUeberpruefung: new Date('2024-06-01'),
        hinweise: 'Grundkenntnisse',
      },
    ],
    fahrzeugkenntnisse: [
      {
        bezeichnung: 'LKW',
        erwerb: new Date('2015-01-01'),
        letzteUeberpruefung: new Date('2023-05-01'),
        naechsteUeberpruefung: new Date('2024-05-01'),
        hinweise: 'Erforderliche Schulungen abgeschlossen',
      },
      {
        bezeichnung: 'PKW',
        erwerb: new Date('2008-01-01'),
        letzteUeberpruefung: new Date('2022-12-01'),
        naechsteUeberpruefung: new Date('2023-12-01'),
        hinweise: 'Regelmäßige Wartung erforderlich',
      },
    ],
    infrastrukturkenntnisse: [
      {
        bezeichnung: 'Verkehrsmanagementsystem',
        erwerb: new Date('2018-01-01'),
        letzteUeberpruefung: new Date('2023-04-01'),
        naechsteUeberpruefung: new Date('2024-04-01'),
        hinweise: 'Erfahrung mit modernen Systemen',
      },
      {
        bezeichnung: 'Zugbeeinflussungssysteme',
        erwerb: new Date('2020-01-01'),
        letzteUeberpruefung: new Date('2023-03-01'),
        naechsteUeberpruefung: new Date('2024-03-01'),
        hinweise: 'Kenntnisse in ETCS',
      },
    ],
  },
  {
    id: 4,
    fuehrerschein: {
      fuehrerscheinNummer: 'DE1234567890',
      status: 'gültig',
    },
    inhaber: {
      name: 'Mustermann',
      vorname: 'Max',
      geburtstag: new Date('1990-01-01'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 4,
      status: 'gültig',
      unbefristet: false,
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Straßenverkehrsamt Musterstadt',
      strasseUndNummer: 'Hauptstraße 1',
      plz: 12345,
      ort: 'Musterstadt',
      telefon: '01234-56789',
      fax: '01234-56789',
      email: 'info@strassenverkehrsamt-musterstadt.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild.jpg',
      unterschrift: 'path/to/unterschrift.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma GmbH',
      strasseUndNummer: 'Industriestraße 10',
      plz: 54321,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '09876-54321',
      fax: '01234-56789',
      email: 'info@musterfirma.de',
      unternehmensKategorie: 'Verkehrsunternehmen',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: true,
      A1: false,
      A2: false,
      A3: false,
      A4: false,
      A5: false,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: '',
    },
    zusaetzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschraenkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    aenderung: {
      datum: new Date('2023-06-01'),
      aenderungFeld3Klasse: 'Neue Klasse hinzugefügt: C',
      aenderungFeld4Angaben: 'Wohnort geändert',
      aenderungFeld5Sprachen: 'Spanisch hinzugefügt',
      aenderungFeld6Einschraenkung: 'Sehhilfe erforderlich',
      aenderungFeld7Fahrzeug: 'Neuer Fahrzeugtyp: LKW',
      aenderungFeld8Infrastruktur: 'Neuer Infrastrukturort hinzugefügt: Berlin',
      sontiges: 'Weitere Änderungen nicht relevant.',
    },
    aussetzung: {
      von: new Date('2023-07-01'),
      bis: new Date('2023-12-31'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: false,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: false,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: false,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: false,
      sontiges: 'Temporäre Aussetzung wegen gesundheitlicher Probleme.',
    },
    entziehung: {
      datum: new Date('2024-01-01'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: true,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: true,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: true,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: true,
      ausscheidenUnternehmen: true,
      sontiges: 'Entziehung wegen schwerwiegender Verstöße.',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2023-01-01'),
        naechsteUntersuchung: new Date('2024-01-01'),
        hinweise: 'Keine besonderen Hinweise.',
      },
      smsSchulung: {
        letzteSchulung: new Date('2022-01-01'),
        naechsteSchulung: new Date('2023-01-01'),
      },
    },
    sprachkenntnisse: [
      {
        bezeichnung: 'Englisch',
        erwerb: new Date('2005-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: 'Fließend in Wort und Schrift',
      },
      {
        bezeichnung: 'Spanisch',
        erwerb: new Date('2010-01-01'),
        letzteUeberpruefung: new Date('2023-06-01'),
        naechsteUeberpruefung: new Date('2024-06-01'),
        hinweise: 'Grundkenntnisse',
      },
    ],
    fahrzeugkenntnisse: [
      {
        bezeichnung: 'LKW',
        erwerb: new Date('2015-01-01'),
        letzteUeberpruefung: new Date('2023-05-01'),
        naechsteUeberpruefung: new Date('2024-05-01'),
        hinweise: 'Erforderliche Schulungen abgeschlossen',
      },
      {
        bezeichnung: 'PKW',
        erwerb: new Date('2008-01-01'),
        letzteUeberpruefung: new Date('2022-12-01'),
        naechsteUeberpruefung: new Date('2023-12-01'),
        hinweise: 'Regelmäßige Wartung erforderlich',
      },
    ],
    infrastrukturkenntnisse: [
      {
        bezeichnung: 'Verkehrsmanagementsystem',
        erwerb: new Date('2018-01-01'),
        letzteUeberpruefung: new Date('2023-04-01'),
        naechsteUeberpruefung: new Date('2024-04-01'),
        hinweise: 'Erfahrung mit modernen Systemen',
      },
      {
        bezeichnung: 'Zugbeeinflussungssysteme',
        erwerb: new Date('2020-01-01'),
        letzteUeberpruefung: new Date('2023-03-01'),
        naechsteUeberpruefung: new Date('2024-03-01'),
        hinweise: 'Kenntnisse in ETCS',
      },
    ],
  },
  {
    id: 5,
    fuehrerschein: {
      fuehrerscheinNummer: 'DE1234567890',
      status: 'gültig',
    },
    inhaber: {
      name: 'Müller',
      vorname: 'Anna',
      geburtstag: new Date('1985-05-15'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 1,
      status: 'gültig',
      unbefristet: false,
      ausstellungsDatum: new Date('2020-01-01'),
      ablaufGueltigkeit: new Date('2021-01-01'),
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Kreisverwaltung Musterland',
      strasseUndNummer: 'Am Rathausplatz 5',
      plz: 54321,
      ort: 'Musterstadt',
      telefon: '07654-32109',
      fax: '01234-56789',
      email: 'info@kreisverwaltung-musterland.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild-anna.jpg',
      unterschrift: 'path/to/unterschrift-anna.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma Logistik AG',
      strasseUndNummer: 'Logistikweg 1',
      plz: 98765,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '01234-98765',
      fax: '01234-56789',
      email: 'info@musterfirma-logistik.de',
      unternehmensKategorie: 'Infrastrukturunternehmen',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: false,
      A1: false,
      A2: false,
      A3: false,
      A4: false,
      A5: true,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: 'Nur mit Automatikgetriebe.',
    },
    zusaetzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschraenkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    aenderung: {
      datum: new Date('2023-06-01'),
      aenderungFeld3Klasse: 'Neue Klasse hinzugefügt: C',
      aenderungFeld4Angaben: 'Wohnort geändert',
      aenderungFeld5Sprachen: 'Spanisch hinzugefügt',
      aenderungFeld6Einschraenkung: 'Sehhilfe erforderlich',
      aenderungFeld7Fahrzeug: 'Neuer Fahrzeugtyp: LKW',
      aenderungFeld8Infrastruktur: 'Neuer Infrastrukturort hinzugefügt: Berlin',
      sontiges: 'Weitere Änderungen nicht relevant.',
    },
    aussetzung: {
      von: new Date('2023-07-01'),
      bis: new Date('2023-12-31'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: false,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: false,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: false,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: false,
      sontiges: 'Temporäre Aussetzung wegen gesundheitlicher Probleme.',
    },
    entziehung: {
      datum: new Date('2024-01-01'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: true,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: true,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: true,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: true,
      ausscheidenUnternehmen: true,
      sontiges: 'Entziehung wegen schwerwiegender Verstöße.',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2022-06-01'),
        naechsteUntersuchung: new Date('2023-06-01'),
        hinweise: 'Brillenträger, Korrektionswerte beachten.',
      },
      smsSchulung: {
        letzteSchulung: new Date('2021-12-01'),
        naechsteSchulung: new Date('2022-12-01'),
      },
    },
    sprachkenntnisse: [
      {
        bezeichnung: 'Englisch',
        erwerb: new Date('2005-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: 'Fließend in Wort und Schrift',
      },
      {
        bezeichnung: 'Spanisch',
        erwerb: new Date('2010-01-01'),
        letzteUeberpruefung: new Date('2023-06-01'),
        naechsteUeberpruefung: new Date('2024-06-01'),
        hinweise: 'Grundkenntnisse',
      },
    ],
    fahrzeugkenntnisse: [
      {
        bezeichnung: 'LKW',
        erwerb: new Date('2015-01-01'),
        letzteUeberpruefung: new Date('2023-05-01'),
        naechsteUeberpruefung: new Date('2024-05-01'),
        hinweise: 'Erforderliche Schulungen abgeschlossen',
      },
      {
        bezeichnung: 'PKW',
        erwerb: new Date('2008-01-01'),
        letzteUeberpruefung: new Date('2022-12-01'),
        naechsteUeberpruefung: new Date('2023-12-01'),
        hinweise: 'Regelmäßige Wartung erforderlich',
      },
    ],
    infrastrukturkenntnisse: [
      {
        bezeichnung: 'Verkehrsmanagementsystem',
        erwerb: new Date('2018-01-01'),
        letzteUeberpruefung: new Date('2023-04-01'),
        naechsteUeberpruefung: new Date('2024-04-01'),
        hinweise: 'Erfahrung mit modernen Systemen',
      },
      {
        bezeichnung: 'Zugbeeinflussungssysteme',
        erwerb: new Date('2020-01-01'),
        letzteUeberpruefung: new Date('2023-03-01'),
        naechsteUeberpruefung: new Date('2024-03-01'),
        hinweise: 'Kenntnisse in ETCS',
      },
    ],
  },
  {
    id: 6,
    fuehrerschein: {
      fuehrerscheinNummer: 'DE1234567890',
      status: 'gültig',
    },
    inhaber: {
      name: 'Schmidt',
      vorname: 'Thomas',
      geburtstag: new Date('1983-09-30'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 2,
      status: 'Entwurf',
      unbefristet: false,
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Stadtverwaltung Musterstadt',
      strasseUndNummer: 'Marktplatz 7',
      plz: 12345,
      ort: 'Musterstadt',
      telefon: '04567-89012',
      fax: '01234-56789',
      email: 'info@stadtverwaltung-musterstadt.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild-thomas.jpg',
      unterschrift: 'path/to/unterschrift-thomas.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma Bau GmbH',
      strasseUndNummer: 'Baustellenweg 3',
      plz: 54321,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '09876-54321',
      fax: '01234-56789',
      email: 'info@musterfirma-bau.de',
      unternehmensKategorie: 'Infrastrukturunternehmen',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: true,
      A1: true,
      A2: false,
      A3: false,
      A4: false,
      A5: false,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: '',
    },
    zusaetzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschraenkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    aenderung: {
      datum: new Date('2023-06-01'),
      aenderungFeld3Klasse: 'Neue Klasse hinzugefügt: C',
      aenderungFeld4Angaben: 'Wohnort geändert',
      aenderungFeld5Sprachen: 'Spanisch hinzugefügt',
      aenderungFeld6Einschraenkung: 'Sehhilfe erforderlich',
      aenderungFeld7Fahrzeug: 'Neuer Fahrzeugtyp: LKW',
      aenderungFeld8Infrastruktur: 'Neuer Infrastrukturort hinzugefügt: Berlin',
      sontiges: 'Weitere Änderungen nicht relevant.',
    },
    aussetzung: {
      von: new Date('2023-07-01'),
      bis: new Date('2023-12-31'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: false,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: false,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: false,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: false,
      sontiges: 'Temporäre Aussetzung wegen gesundheitlicher Probleme.',
    },
    entziehung: {
      datum: new Date('2024-01-01'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: true,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: true,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: true,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: true,
      ausscheidenUnternehmen: true,
      sontiges: 'Entziehung wegen schwerwiegender Verstöße.',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2023-05-01'),
        naechsteUntersuchung: new Date('2024-05-01'),
        hinweise: '',
      },
      smsSchulung: {
        letzteSchulung: new Date('2022-03-01'),
        naechsteSchulung: new Date('2023-03-01'),
      },
    },
    sprachkenntnisse: [
      {
        bezeichnung: 'Englisch',
        erwerb: new Date('2005-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: 'Fließend in Wort und Schrift',
      },
      {
        bezeichnung: 'Spanisch',
        erwerb: new Date('2010-01-01'),
        letzteUeberpruefung: new Date('2023-06-01'),
        naechsteUeberpruefung: new Date('2024-06-01'),
        hinweise: 'Grundkenntnisse',
      },
    ],
    fahrzeugkenntnisse: [
      {
        bezeichnung: 'LKW',
        erwerb: new Date('2015-01-01'),
        letzteUeberpruefung: new Date('2023-05-01'),
        naechsteUeberpruefung: new Date('2024-05-01'),
        hinweise: 'Erforderliche Schulungen abgeschlossen',
      },
      {
        bezeichnung: 'PKW',
        erwerb: new Date('2008-01-01'),
        letzteUeberpruefung: new Date('2022-12-01'),
        naechsteUeberpruefung: new Date('2023-12-01'),
        hinweise: 'Regelmäßige Wartung erforderlich',
      },
    ],
    infrastrukturkenntnisse: [
      {
        bezeichnung: 'Verkehrsmanagementsystem',
        erwerb: new Date('2018-01-01'),
        letzteUeberpruefung: new Date('2023-04-01'),
        naechsteUeberpruefung: new Date('2024-04-01'),
        hinweise: 'Erfahrung mit modernen Systemen',
      },
      {
        bezeichnung: 'Zugbeeinflussungssysteme',
        erwerb: new Date('2020-01-01'),
        letzteUeberpruefung: new Date('2023-03-01'),
        naechsteUeberpruefung: new Date('2024-03-01'),
        hinweise: 'Kenntnisse in ETCS',
      },
    ],
  },
  {
    id: 7,
    fuehrerschein: {
      fuehrerscheinNummer: 'DE1234567890',
      status: 'gültig',
    },
    inhaber: {
      name: 'Mustermann',
      vorname: 'Max',
      geburtstag: new Date('1990-01-01'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 3,
      status: 'gültig',
      unbefristet: false,
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Straßenverkehrsamt Musterstadt',
      strasseUndNummer: 'Hauptstraße 1',
      plz: 12345,
      ort: 'Musterstadt',
      telefon: '01234-56789',
      fax: '01234-56789',
      email: 'info@strassenverkehrsamt-musterstadt.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild.jpg',
      unterschrift: 'path/to/unterschrift.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma GmbH',
      strasseUndNummer: 'Industriestraße 10',
      plz: 54321,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '09876-54321',
      fax: '01234-56789',
      email: 'info@musterfirma.de',
      unternehmensKategorie: 'Infrastrukturunternehmen',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: true,
      A1: false,
      A2: false,
      A3: false,
      A4: false,
      A5: false,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: '',
    },
    zusaetzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschraenkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    aenderung: {
      datum: new Date('2023-06-01'),
      aenderungFeld3Klasse: 'Neue Klasse hinzugefügt: C',
      aenderungFeld4Angaben: 'Wohnort geändert',
      aenderungFeld5Sprachen: 'Spanisch hinzugefügt',
      aenderungFeld6Einschraenkung: 'Sehhilfe erforderlich',
      aenderungFeld7Fahrzeug: 'Neuer Fahrzeugtyp: LKW',
      aenderungFeld8Infrastruktur: 'Neuer Infrastrukturort hinzugefügt: Berlin',
      sontiges: 'Weitere Änderungen nicht relevant.',
    },
    aussetzung: {
      von: new Date('2023-07-01'),
      bis: new Date('2023-12-31'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: false,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: false,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: false,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: false,
      sontiges: 'Temporäre Aussetzung wegen gesundheitlicher Probleme.',
    },
    entziehung: {
      datum: new Date('2024-01-01'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: true,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: true,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: true,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: true,
      ausscheidenUnternehmen: true,
      sontiges: 'Entziehung wegen schwerwiegender Verstöße.',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2023-01-01'),
        naechsteUntersuchung: new Date('2024-01-01'),
        hinweise: 'Keine besonderen Hinweise.',
      },
      smsSchulung: {
        letzteSchulung: new Date('2022-01-01'),
        naechsteSchulung: new Date('2023-01-01'),
      },
    },
    sprachkenntnisse: [
      {
        bezeichnung: 'Englisch',
        erwerb: new Date('2005-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: 'Fließend in Wort und Schrift',
      },
      {
        bezeichnung: 'Spanisch',
        erwerb: new Date('2010-01-01'),
        letzteUeberpruefung: new Date('2023-06-01'),
        naechsteUeberpruefung: new Date('2024-06-01'),
        hinweise: 'Grundkenntnisse',
      },
    ],
    fahrzeugkenntnisse: [
      {
        bezeichnung: 'LKW',
        erwerb: new Date('2015-01-01'),
        letzteUeberpruefung: new Date('2023-05-01'),
        naechsteUeberpruefung: new Date('2024-05-01'),
        hinweise: 'Erforderliche Schulungen abgeschlossen',
      },
      {
        bezeichnung: 'PKW',
        erwerb: new Date('2008-01-01'),
        letzteUeberpruefung: new Date('2022-12-01'),
        naechsteUeberpruefung: new Date('2023-12-01'),
        hinweise: 'Regelmäßige Wartung erforderlich',
      },
    ],
    infrastrukturkenntnisse: [
      {
        bezeichnung: 'Verkehrsmanagementsystem',
        erwerb: new Date('2018-01-01'),
        letzteUeberpruefung: new Date('2023-04-01'),
        naechsteUeberpruefung: new Date('2024-04-01'),
        hinweise: 'Erfahrung mit modernen Systemen',
      },
      {
        bezeichnung: 'Zugbeeinflussungssysteme',
        erwerb: new Date('2020-01-01'),
        letzteUeberpruefung: new Date('2023-03-01'),
        naechsteUeberpruefung: new Date('2024-03-01'),
        hinweise: 'Kenntnisse in ETCS',
      },
    ],
  },
  {
    id: 8,
    fuehrerschein: {
      fuehrerscheinNummer: 'DE1234567890',
      status: 'gültig',
    },
    inhaber: {
      name: 'Müller',
      vorname: 'Anna',
      geburtstag: new Date('1985-05-15'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 2,
      status: 'gültig',
      unbefristet: false,
      ausstellungsDatum: new Date('2020-01-01'),
      ablaufGueltigkeit: new Date('2021-01-01'),
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Kreisverwaltung Musterland',
      strasseUndNummer: 'Am Rathausplatz 5',
      plz: 54321,
      ort: 'Musterstadt',
      telefon: '07654-32109',
      fax: '01234-56789',
      email: 'info@kreisverwaltung-musterland.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild-anna.jpg',
      unterschrift: 'path/to/unterschrift-anna.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma Logistik AG',
      strasseUndNummer: 'Logistikweg 1',
      plz: 98765,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '01234-98765',
      fax: '01234-56789',
      email: 'info@musterfirma-logistik.de',
      unternehmensKategorie: 'Infrastrukturunternehmen',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: false,
      A1: false,
      A2: false,
      A3: false,
      A4: false,
      A5: true,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: 'Nur mit Automatikgetriebe.',
    },
    zusaetzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschraenkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    aenderung: {
      datum: new Date('2023-06-01'),
      aenderungFeld3Klasse: 'Neue Klasse hinzugefügt: C',
      aenderungFeld4Angaben: 'Wohnort geändert',
      aenderungFeld5Sprachen: 'Spanisch hinzugefügt',
      aenderungFeld6Einschraenkung: 'Sehhilfe erforderlich',
      aenderungFeld7Fahrzeug: 'Neuer Fahrzeugtyp: LKW',
      aenderungFeld8Infrastruktur: 'Neuer Infrastrukturort hinzugefügt: Berlin',
      sontiges: 'Weitere Änderungen nicht relevant.',
    },
    aussetzung: {
      von: new Date('2023-07-01'),
      bis: new Date('2023-12-31'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: false,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: false,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: false,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: false,
      sontiges: 'Temporäre Aussetzung wegen gesundheitlicher Probleme.',
    },
    entziehung: {
      datum: new Date('2024-01-01'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: true,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: true,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: true,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: true,
      ausscheidenUnternehmen: true,
      sontiges: 'Entziehung wegen schwerwiegender Verstöße.',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2022-06-01'),
        naechsteUntersuchung: new Date('2023-06-01'),
        hinweise: 'Brillenträger, Korrektionswerte beachten.',
      },
      smsSchulung: {
        letzteSchulung: new Date('2021-12-01'),
        naechsteSchulung: new Date('2022-12-01'),
      },
    },
    sprachkenntnisse: [
      {
        bezeichnung: 'Englisch',
        erwerb: new Date('2005-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: 'Fließend in Wort und Schrift',
      },
      {
        bezeichnung: 'Spanisch',
        erwerb: new Date('2010-01-01'),
        letzteUeberpruefung: new Date('2023-06-01'),
        naechsteUeberpruefung: new Date('2024-06-01'),
        hinweise: 'Grundkenntnisse',
      },
    ],
    fahrzeugkenntnisse: [
      {
        bezeichnung: 'LKW',
        erwerb: new Date('2015-01-01'),
        letzteUeberpruefung: new Date('2023-05-01'),
        naechsteUeberpruefung: new Date('2024-05-01'),
        hinweise: 'Erforderliche Schulungen abgeschlossen',
      },
      {
        bezeichnung: 'PKW',
        erwerb: new Date('2008-01-01'),
        letzteUeberpruefung: new Date('2022-12-01'),
        naechsteUeberpruefung: new Date('2023-12-01'),
        hinweise: 'Regelmäßige Wartung erforderlich',
      },
    ],
    infrastrukturkenntnisse: [
      {
        bezeichnung: 'Verkehrsmanagementsystem',
        erwerb: new Date('2018-01-01'),
        letzteUeberpruefung: new Date('2023-04-01'),
        naechsteUeberpruefung: new Date('2024-04-01'),
        hinweise: 'Erfahrung mit modernen Systemen',
      },
      {
        bezeichnung: 'Zugbeeinflussungssysteme',
        erwerb: new Date('2020-01-01'),
        letzteUeberpruefung: new Date('2023-03-01'),
        naechsteUeberpruefung: new Date('2024-03-01'),
        hinweise: 'Kenntnisse in ETCS',
      },
    ],
  },
  {
    id: 9,
    fuehrerschein: {
      fuehrerscheinNummer: 'DE1234567890',
      status: 'gültig',
    },
    inhaber: {
      name: 'Schmidt',
      vorname: 'Thomas',
      geburtstag: new Date('1983-09-30'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 3,
      status: 'Entwurf',
      unbefristet: false,
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Stadtverwaltung Musterstadt',
      strasseUndNummer: 'Marktplatz 7',
      plz: 12345,
      ort: 'Musterstadt',
      telefon: '04567-89012',
      fax: '01234-56789',
      email: 'info@stadtverwaltung-musterstadt.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild-thomas.jpg',
      unterschrift: 'path/to/unterschrift-thomas.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma Bau GmbH',
      strasseUndNummer: 'Baustellenweg 3',
      plz: 54321,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '09876-54321',
      fax: '01234-56789',
      email: 'info@musterfirma-bau.de',
      unternehmensKategorie: 'Verkehrsunternehmen',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: true,
      A1: true,
      A2: false,
      A3: false,
      A4: false,
      A5: false,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: '',
    },
    zusaetzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschraenkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    aenderung: {
      datum: new Date('2023-06-01'),
      aenderungFeld3Klasse: 'Neue Klasse hinzugefügt: C',
      aenderungFeld4Angaben: 'Wohnort geändert',
      aenderungFeld5Sprachen: 'Spanisch hinzugefügt',
      aenderungFeld6Einschraenkung: 'Sehhilfe erforderlich',
      aenderungFeld7Fahrzeug: 'Neuer Fahrzeugtyp: LKW',
      aenderungFeld8Infrastruktur: 'Neuer Infrastrukturort hinzugefügt: Berlin',
      sontiges: 'Weitere Änderungen nicht relevant.',
    },
    aussetzung: {
      von: new Date('2023-07-01'),
      bis: new Date('2023-12-31'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: false,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: false,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: false,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: false,
      sontiges: 'Temporäre Aussetzung wegen gesundheitlicher Probleme.',
    },
    entziehung: {
      datum: new Date('2024-01-01'),
      wegfallFuehrerschein: true,
      wegfallNachweisAllgemeinKenntnisse: true,
      wegfallNachweisBefaehigung: true,
      wegfallNachweisBetriebsverfahren: true,
      wegfallNachweisZugbeeinflussungSysteme: true,
      wegfallNachweisSignalSysteme: true,
      wegfallNachweisSchulung: true,
      wegfallNachweisSprachkenntnisse: true,
      ausscheidenUnternehmen: true,
      sontiges: 'Entziehung wegen schwerwiegender Verstöße.',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2023-05-01'),
        naechsteUntersuchung: new Date('2024-05-01'),
        hinweise: '',
      },
      smsSchulung: {
        letzteSchulung: new Date('2022-03-01'),
        naechsteSchulung: new Date('2023-03-01'),
      },
    },
    sprachkenntnisse: [
      {
        bezeichnung: 'Englisch',
        erwerb: new Date('2005-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: 'Fließend in Wort und Schrift',
      },
      {
        bezeichnung: 'Spanisch',
        erwerb: new Date('2010-01-01'),
        letzteUeberpruefung: new Date('2023-06-01'),
        naechsteUeberpruefung: new Date('2024-06-01'),
        hinweise: 'Grundkenntnisse',
      },
    ],
    fahrzeugkenntnisse: [
      {
        bezeichnung: 'LKW',
        erwerb: new Date('2015-01-01'),
        letzteUeberpruefung: new Date('2023-05-01'),
        naechsteUeberpruefung: new Date('2024-05-01'),
        hinweise: 'Erforderliche Schulungen abgeschlossen',
      },
      {
        bezeichnung: 'PKW',
        erwerb: new Date('2008-01-01'),
        letzteUeberpruefung: new Date('2022-12-01'),
        naechsteUeberpruefung: new Date('2023-12-01'),
        hinweise: 'Regelmäßige Wartung erforderlich',
      },
    ],
    infrastrukturkenntnisse: [
      {
        bezeichnung: 'Verkehrsmanagementsystem',
        erwerb: new Date('2018-01-01'),
        letzteUeberpruefung: new Date('2023-04-01'),
        naechsteUeberpruefung: new Date('2024-04-01'),
        hinweise: 'Erfahrung mit modernen Systemen',
      },
      {
        bezeichnung: 'Zugbeeinflussungssysteme',
        erwerb: new Date('2020-01-01'),
        letzteUeberpruefung: new Date('2023-03-01'),
        naechsteUeberpruefung: new Date('2024-03-01'),
        hinweise: 'Kenntnisse in ETCS',
      },
    ],
  },
]
