import { Person } from '../types/types'

export const fakeDate: Person[] = [
  {
    id: 1,
    fuehrerschein: {
      fuehrerscheinNummer: '12345',
      status: 'gültig',
    },
    inhaber: {
      name: 'Mustermann',
      vorname: 'Max',
      geburtstag: new Date('1990-01-01'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 'ZB-123',
      status: 'gültig',
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Straßenverkehrsamt Musterstadt',
      strasseUndNummer: 'Hauptstraße 1',
      plz: 12345,
      ort: 'Musterstadt',
      telefon: '01234-56789',
      email: 'info@strassenverkehrsamt-musterstadt.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild.jpg',
      unterschrift: 'path/to/unterschrift.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma GmbH',
      strasseUndNummer: 'Industriestraße 10',
      plz: 54321,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '09876-54321',
      email: 'info@musterfirma.de',
      unternehmensKategorie: 'Dienstleistungen',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: true,
      A1: false,
      A2: false,
      A3: false,
      A4: false,
      A5: false,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: '',
    },
    zusätzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschränkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2023-01-01'),
        naechsteUntersuchung: new Date('2024-01-01'),
        hinweise: 'Keine besonderen Hinweise.',
      },
      smsSchulung: {
        letzteSchulung: new Date('2022-01-01'),
        naechsteSchulung: new Date('2023-01-01'),
      },
    },
    sprachkenntnisse: {
      sprache1: {
        bezeichnung: 'Englisch',
        erwerb: new Date('2005-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: '',
      },
    },
  },
  {
    id: 2,
    fuehrerschein: {
      fuehrerscheinNummer: '54321',
      status: 'ungültig',
    },
    inhaber: {
      name: 'Müller',
      vorname: 'Anna',
      geburtstag: new Date('1985-05-15'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 'ZB-456',
      status: 'abgelaufen',
      ausstellungsDatum: new Date('2020-01-01'),
      ablaufGueltigkeit: new Date('2021-01-01'),
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Kreisverwaltung Musterland',
      strasseUndNummer: 'Am Rathausplatz 5',
      plz: 54321,
      ort: 'Musterstadt',
      telefon: '07654-32109',
      email: 'info@kreisverwaltung-musterland.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild-anna.jpg',
      unterschrift: 'path/to/unterschrift-anna.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma Logistik AG',
      strasseUndNummer: 'Logistikweg 1',
      plz: 98765,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '01234-98765',
      email: 'info@musterfirma-logistik.de',
      unternehmensKategorie: 'Logistik',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: false,
      A1: false,
      A2: false,
      A3: false,
      A4: false,
      A5: true,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: 'Nur mit Automatikgetriebe.',
    },
    zusätzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschränkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2022-06-01'),
        naechsteUntersuchung: new Date('2023-06-01'),
        hinweise: 'Brillenträger, Korrektionswerte beachten.',
      },
      smsSchulung: {
        letzteSchulung: new Date('2021-12-01'),
        naechsteSchulung: new Date('2022-12-01'),
      },
    },
    sprachkenntnisse: {
      sprache1: {
        bezeichnung: 'Spanisch',
        erwerb: new Date('2008-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: 'Fließend in Wort und Schrift.',
      },
    },
  },
  {
    id: 3,
    fuehrerschein: {
      fuehrerscheinNummer: '67890',
      status: 'gültig',
    },
    inhaber: {
      name: 'Schmidt',
      vorname: 'Thomas',
      geburtstag: new Date('1983-09-30'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 'ZB-789',
      status: 'Entwurf',
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Stadtverwaltung Musterstadt',
      strasseUndNummer: 'Marktplatz 7',
      plz: 12345,
      ort: 'Musterstadt',
      telefon: '04567-89012',
      email: 'info@stadtverwaltung-musterstadt.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild-thomas.jpg',
      unterschrift: 'path/to/unterschrift-thomas.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma Bau GmbH',
      strasseUndNummer: 'Baustellenweg 3',
      plz: 54321,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '09876-54321',
      email: 'info@musterfirma-bau.de',
      unternehmensKategorie: 'Bauwesen',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: true,
      A1: true,
      A2: false,
      A3: false,
      A4: false,
      A5: false,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: '',
    },
    zusätzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschränkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2023-05-01'),
        naechsteUntersuchung: new Date('2024-05-01'),
        hinweise: '',
      },
      smsSchulung: {
        letzteSchulung: new Date('2022-03-01'),
        naechsteSchulung: new Date('2023-03-01'),
      },
    },
    sprachkenntnisse: {
      sprache1: {
        bezeichnung: 'Französisch',
        erwerb: new Date('2006-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: '',
      },
    },
  },
  {
    id: 4,
    fuehrerschein: {
      fuehrerscheinNummer: '12345',
      status: 'gültig',
    },
    inhaber: {
      name: 'Mustermann',
      vorname: 'Max',
      geburtstag: new Date('1990-01-01'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 'ZB-123',
      status: 'gültig',
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Straßenverkehrsamt Musterstadt',
      strasseUndNummer: 'Hauptstraße 1',
      plz: 12345,
      ort: 'Musterstadt',
      telefon: '01234-56789',
      email: 'info@strassenverkehrsamt-musterstadt.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild.jpg',
      unterschrift: 'path/to/unterschrift.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma GmbH',
      strasseUndNummer: 'Industriestraße 10',
      plz: 54321,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '09876-54321',
      email: 'info@musterfirma.de',
      unternehmensKategorie: 'Dienstleistungen',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: true,
      A1: false,
      A2: false,
      A3: false,
      A4: false,
      A5: false,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: '',
    },
    zusätzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschränkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2023-01-01'),
        naechsteUntersuchung: new Date('2024-01-01'),
        hinweise: 'Keine besonderen Hinweise.',
      },
      smsSchulung: {
        letzteSchulung: new Date('2022-01-01'),
        naechsteSchulung: new Date('2023-01-01'),
      },
    },
    sprachkenntnisse: {
      sprache1: {
        bezeichnung: 'Englisch',
        erwerb: new Date('2005-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: '',
      },
    },
  },
  {
    id: 5,
    fuehrerschein: {
      fuehrerscheinNummer: '54321',
      status: 'ungültig',
    },
    inhaber: {
      name: 'Müller',
      vorname: 'Anna',
      geburtstag: new Date('1985-05-15'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 'ZB-456',
      status: 'abgelaufen',
      ausstellungsDatum: new Date('2020-01-01'),
      ablaufGueltigkeit: new Date('2021-01-01'),
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Kreisverwaltung Musterland',
      strasseUndNummer: 'Am Rathausplatz 5',
      plz: 54321,
      ort: 'Musterstadt',
      telefon: '07654-32109',
      email: 'info@kreisverwaltung-musterland.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild-anna.jpg',
      unterschrift: 'path/to/unterschrift-anna.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma Logistik AG',
      strasseUndNummer: 'Logistikweg 1',
      plz: 98765,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '01234-98765',
      email: 'info@musterfirma-logistik.de',
      unternehmensKategorie: 'Logistik',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: false,
      A1: false,
      A2: false,
      A3: false,
      A4: false,
      A5: true,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: 'Nur mit Automatikgetriebe.',
    },
    zusätzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschränkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2022-06-01'),
        naechsteUntersuchung: new Date('2023-06-01'),
        hinweise: 'Brillenträger, Korrektionswerte beachten.',
      },
      smsSchulung: {
        letzteSchulung: new Date('2021-12-01'),
        naechsteSchulung: new Date('2022-12-01'),
      },
    },
    sprachkenntnisse: {
      sprache1: {
        bezeichnung: 'Spanisch',
        erwerb: new Date('2008-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: 'Fließend in Wort und Schrift.',
      },
    },
  },
  {
    id: 6,
    fuehrerschein: {
      fuehrerscheinNummer: '67890',
      status: 'gültig',
    },
    inhaber: {
      name: 'Schmidt',
      vorname: 'Thomas',
      geburtstag: new Date('1983-09-30'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 'ZB-789',
      status: 'Entwurf',
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Stadtverwaltung Musterstadt',
      strasseUndNummer: 'Marktplatz 7',
      plz: 12345,
      ort: 'Musterstadt',
      telefon: '04567-89012',
      email: 'info@stadtverwaltung-musterstadt.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild-thomas.jpg',
      unterschrift: 'path/to/unterschrift-thomas.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma Bau GmbH',
      strasseUndNummer: 'Baustellenweg 3',
      plz: 54321,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '09876-54321',
      email: 'info@musterfirma-bau.de',
      unternehmensKategorie: 'Bauwesen',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: true,
      A1: true,
      A2: false,
      A3: false,
      A4: false,
      A5: false,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: '',
    },
    zusätzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschränkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2023-05-01'),
        naechsteUntersuchung: new Date('2024-05-01'),
        hinweise: '',
      },
      smsSchulung: {
        letzteSchulung: new Date('2022-03-01'),
        naechsteSchulung: new Date('2023-03-01'),
      },
    },
    sprachkenntnisse: {
      sprache1: {
        bezeichnung: 'Französisch',
        erwerb: new Date('2006-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: '',
      },
    },
  },
  {
    id: 7,
    fuehrerschein: {
      fuehrerscheinNummer: '12345',
      status: 'gültig',
    },
    inhaber: {
      name: 'Mustermann',
      vorname: 'Max',
      geburtstag: new Date('1990-01-01'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 'ZB-123',
      status: 'gültig',
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Straßenverkehrsamt Musterstadt',
      strasseUndNummer: 'Hauptstraße 1',
      plz: 12345,
      ort: 'Musterstadt',
      telefon: '01234-56789',
      email: 'info@strassenverkehrsamt-musterstadt.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild.jpg',
      unterschrift: 'path/to/unterschrift.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma GmbH',
      strasseUndNummer: 'Industriestraße 10',
      plz: 54321,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '09876-54321',
      email: 'info@musterfirma.de',
      unternehmensKategorie: 'Dienstleistungen',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: true,
      A1: false,
      A2: false,
      A3: false,
      A4: false,
      A5: false,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: '',
    },
    zusätzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschränkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2023-01-01'),
        naechsteUntersuchung: new Date('2024-01-01'),
        hinweise: 'Keine besonderen Hinweise.',
      },
      smsSchulung: {
        letzteSchulung: new Date('2022-01-01'),
        naechsteSchulung: new Date('2023-01-01'),
      },
    },
    sprachkenntnisse: {
      sprache1: {
        bezeichnung: 'Englisch',
        erwerb: new Date('2005-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: '',
      },
    },
  },
  {
    id: 8,
    fuehrerschein: {
      fuehrerscheinNummer: '54321',
      status: 'ungültig',
    },
    inhaber: {
      name: 'Müller',
      vorname: 'Anna',
      geburtstag: new Date('1985-05-15'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 'ZB-456',
      status: 'abgelaufen',
      ausstellungsDatum: new Date('2020-01-01'),
      ablaufGueltigkeit: new Date('2021-01-01'),
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Kreisverwaltung Musterland',
      strasseUndNummer: 'Am Rathausplatz 5',
      plz: 54321,
      ort: 'Musterstadt',
      telefon: '07654-32109',
      email: 'info@kreisverwaltung-musterland.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild-anna.jpg',
      unterschrift: 'path/to/unterschrift-anna.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma Logistik AG',
      strasseUndNummer: 'Logistikweg 1',
      plz: 98765,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '01234-98765',
      email: 'info@musterfirma-logistik.de',
      unternehmensKategorie: 'Logistik',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: false,
      A1: false,
      A2: false,
      A3: false,
      A4: false,
      A5: true,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: 'Nur mit Automatikgetriebe.',
    },
    zusätzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschränkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2022-06-01'),
        naechsteUntersuchung: new Date('2023-06-01'),
        hinweise: 'Brillenträger, Korrektionswerte beachten.',
      },
      smsSchulung: {
        letzteSchulung: new Date('2021-12-01'),
        naechsteSchulung: new Date('2022-12-01'),
      },
    },
    sprachkenntnisse: {
      sprache1: {
        bezeichnung: 'Spanisch',
        erwerb: new Date('2008-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: 'Fließend in Wort und Schrift.',
      },
    },
  },
  {
    id: 9,
    fuehrerschein: {
      fuehrerscheinNummer: '67890',
      status: 'gültig',
    },
    inhaber: {
      name: 'Schmidt',
      vorname: 'Thomas',
      geburtstag: new Date('1983-09-30'),
      geburtsort: 'Musterstadt',
      staatsangehoerigkeit: 'Deutsch',
    },
    zusatzbescheinigung: {
      nummer: 'ZB-789',
      status: 'Entwurf',
    },
    ausstellendeOrganisationseinheit: {
      bezeichnung: 'Stadtverwaltung Musterstadt',
      strasseUndNummer: 'Marktplatz 7',
      plz: 12345,
      ort: 'Musterstadt',
      telefon: '04567-89012',
      email: 'info@stadtverwaltung-musterstadt.de',
    },
    bilder: {
      lichtBild: 'path/to/lichtbild-thomas.jpg',
      unterschrift: 'path/to/unterschrift-thomas.jpg',
    },
    verantwortlichesUnternehmen: {
      bezeichnung: 'Musterfirma Bau GmbH',
      strasseUndNummer: 'Baustellenweg 3',
      plz: 54321,
      ort: 'Musterstadt',
      land: 'Deutschland',
      telefon: '09876-54321',
      email: 'info@musterfirma-bau.de',
      unternehmensKategorie: 'Bauwesen',
      arbeitsort: 'Musterstadt',
    },
    klasse: {
      A: true,
      A1: true,
      A2: false,
      A3: false,
      A4: false,
      A5: false,
      B: true,
      B1: false,
      B2: false,
      hinweiseKlasseA5: '',
    },
    zusätzlicheAngaben: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    einschränkungen: {
      zelle1: '',
      zelle2: '',
      zelle3: '',
    },
    weitereAngaben: {
      tauglichkeit: {
        letzteUntersuchung: new Date('2023-05-01'),
        naechsteUntersuchung: new Date('2024-05-01'),
        hinweise: '',
      },
      smsSchulung: {
        letzteSchulung: new Date('2022-03-01'),
        naechsteSchulung: new Date('2023-03-01'),
      },
    },
    sprachkenntnisse: {
      sprache1: {
        bezeichnung: 'Französisch',
        erwerb: new Date('2006-01-01'),
        letzteUeberpruefung: new Date('2023-01-01'),
        naechsteUeberpruefung: new Date('2024-01-01'),
        hinweise: '',
      },
    },
  },
]
